check50:
  files: &check50_files
    - !exclude '*.pyc'
    - !exclude '__pycache__'
    - !require application.py
    - !require templates/layout.html
    - !require templates/index.html
    - !require templates/cross.html
    - !require static/styles.css

submit50:
  files: *check50_files
